version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
      linting-and-formatting:
        patterns:
          - "eslint*"
          - "prettier*"
          - "@typescript-eslint/*"
          - "stylelint*"
      testing:
        patterns:
          - "jest*"
          - "@jest/*"
          - "vitest*"
          - "mocha*"
          - "chai*"
          - "cypress*"
          - "playwright*"
